### ISSUE TITLE
Issue: Next job missing from your Resume :) - maybe this one?

### ISSUE THREAD

**Issue by fferas** [juanibiapina/resume#1]
Hi Juan,

I saw your background here and work at Globo and Babbel raised my attention. I work with the Engineering Manager of an AI company and I think he would be interested in your background.

The team works with AI, neural networks to improve the customer experience of their clients - several big names globally. The office in Berlin is new, hiring the first couple of engineers now. The HQ in London grew rapidly from 20 to 40 people over the last year, the company has good potential. Funding is secured.

While the company already has a service on the market, there's still lots to be done to move it to the next level. The service team needs new engineers with similar background like yours.
Tech stack: RoR, React, microservices, Redis, ElasticSearch, Kubernetes.
Details: http://bit.ly/Fullstack_RubyReact_devBuddies

What do you think? Is it something you would be interested to discuss further? I'm happy to tell more on a call.

Best wishes,
Ferenc

**Comment by juanibiapina** [comment]
Sorry, for some reason I missed this. I'm not looking for anything right now, but I appreciate you reaching out :)
